version: '3.8'

services:
  db:
    container_name: postgres-13.6
    image: postgres:13.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: item_db
    ports:
      - "54321:5432"
  app:
    container_name: application
    image: 60081362/fastapipostgres:0.1
    depends_on:
      - db
    ports:
      - "8888:8080"
    environment:
      POSTGRES_HOST: db
    command: bash -c "python -i add_table.py && python main.py"