version: '3.8'

services:
  db:
    container_name: postgres-13.6
    image: postgres:13.6
    restart: always
    env_file:
      - .env
    ports:
      - "54321:5432"
  app:
    container_name: application
    image: 60081362/fastapipostgres:0.2
    depends_on:
      - db
    ports:
      - "8888:8080"
    environment:
      POSTGRES_HOST: db
    env_file:
      - .env
    command: bash -c "python -i add_table.py && python main.py"